#!/bin/bash
#
# Bar Ain't Recursive panel
# by Ivan Sokolov
#

function A {
	echo -n "%{A:$2:}$1%{A}"
}

function B {
	echo -n "%{B#$2}$1%{B-}"
}

function F {
	echo -n "%{F#$2}$1%{F-}"
}

function o {
	echo "%{+o}$1%{-o}"
}

function u {
	echo "%{+u}$1%{-u}"
}

###

DIV=$(F '|' 'ff404040')

###

network() {
	ping -c 1 8.8.8.8 >/dev/null 2>&1 && echo -n $(F + ff00ff00) || echo -n $(F - ffff0000)
}

calendar() {
	DATE=$(date -u +%d/%m/%y)
	echo -n $(F $DATE ffffffff)
}

clock() {
	TIME=$(date -u +%H:%M)
	echo -n $(F $TIME ffffffff)
}

volume() {
	VOLUME=$(pamixer --get-volume)
	echo -n "$(A $(F $VOLUME ffffffff) volume)"
}

battery() {
	BATTERY=$(acpi -b | awk '{gsub(/%,/,""); print $4}' | sed 's/%//g')
	if [[ $BATTERY -gt 20 ]]
	then
		BCOLOR=ffffff
	else
		BCOLOR=ff0000
	fi
	echo -n $(F $BATTERY ff$BCOLOR)
}

layout() {
	echo -n "$(A $(F $(xkb-switch) ffffffff) layout)"
}

mpc_status() {
	if [[ -n $(mpc | grep playing) ]]
	then
		echo -n "$(F "$(mpc current -f '[%title% - %album% - %artist%]|[%file%]')" ffffffff)"
	else
		echo -n ''
	fi
}

mpc_controls() {
	echo -n ''
}

while true
do
	# Left
	printf '%s' '%{l}'
	# Desktops
	for i in 1 2 3 4 5
	do
		printf ' %s' "%{A:$i:}$(F \| ff404040)$(F $i ffffffff)$(F \| ff404040)%{A}"
	done
	
	# Center
	printf '%s' '%{c}'
	printf '%s' "$(mpc_status)"
	# printf '%s' "$(mpc_controls)"
	
	# Right
	printf '%s' '%{r}'
	printf ' %s' $(network) $DIV 
	printf ' %s' $(layout) $DIV
	printf ' %s' $(volume) $DIV 
	# printf ' %s' $(battery) $DIV 
	printf ' %s' $(clock)
	printf ' %s \n' $(calendar)

	sleep 0.5s
done | bar-aint-recursive \
	-F "#ff$ACTIVE" \
	-B "#ff202020" \
	-g 1346x20+10+10 \
	-f '-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-u' | ~/.config/bspwm/spawner
