#!/bin/bash

# Borders and spacing
bspc config border_width 2
bspc config window_gap   20

bspc config top_padding    10
bspc config right_padding  10
bspc config bottom_padding 10
bspc config left_padding   10

# Desktops
for mon in $(bspc query -M); do
	bspc monitor $mon -d web rest
done

#bspc desktop web -l monocle
#bspc desktop rest -l tiled

bspc config gapless_monocle    true
bspc config borderless_monocle true

# Rules
bspc rule -a feh floating=true

# Something else
bspc config split_ratio           0.50
bspc config focus_follows_pointer true

# Colors
bspc config focused_border_color $(gxc boldblack \#)
bspc config active_border_color  $(gxc black \#)
bspc config normal_border_color  $(gxc black \#)
bspc config presel_border_color  $(gxc black \#)

bspc config focused_locked_border_color $(gxc red \#)
bspc config active_locked_border_color  $(gxc boldred \#)
bspc config normal_locked_border_color  $(gxc boldred \#)

bspc config focused_sticky_border_color $(gxc boldgreen \#)
bspc config active_sticky_border_color  $(gxc green \#)
bspc config normal_sticky_border_color  $(gxc green \#)

bspc config focused_private_border_color $(gxc magenta \#)
bspc config active_private_border_color  $(gxc boldmagenta \#)
bspc config normal_private_border_color  $(gxc boldmagenta \#)

bspc config urgent_border_color $(gxc white \#)

# Fix for Java Swing applications
wmname LG3D
export _JAVA_OPTIONS=<<EOF
-Dawt.useSystemAAFontSettings=on
-Dswing.aatext=true
-Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
EOF
export _JAVA_AWT_WM_NONREPAINTING=1
