#!/bin/bash
#
# Bar Ain't Recursive panel
# by Ivan Sokolov
#

WHITE=f8f8f8
RED=a54242
GREEN=8c9440
BLACK=202020
GRAY=404040

# WHITE=202020
# RED=a54242
# GREEN=8c9440
# BLACK=f8f8f8
# GRAY=a0a0a0

function A {
	echo -n "%{A:$2:}$1%{A}"
}

function B {
	echo -n "%{B#ff$2}$1%{B-}"
}

function F {
	echo -n "%{F#ff$2}$1%{F-}"
}

function o {
	echo -n "%{+o}$1%{-o}"
}

function u {
	echo -n  "%{+u}$1%{-u}"
}

###

DIV=$(F '|' $GRAY)

###

network() {
	ping -c 1 8.8.8.8 >/dev/null 2>&1 && echo -n $(F + $GREEN) || echo -n $(F - $RED)
}

calendar() {
	echo -n $(date -u '+%H:%M %d/%m/%y')
}

volume() {
	VOLUME=$(pamixer --get-volume)
	if [[ $(pamixer --get-mute) -eq 'true' ]]
	then
		VCOLOR=$WHITE
	else
		VCOLOR=$GRAY
	fi
	echo -n "$(A $(F $VOLUME $VCOLOR) volume)"
}

battery() {
	BATTERY=$(acpi -b | awk '{gsub(/%,/,""); print $4}' | sed 's/%//g')
	if [[ $BATTERY -gt 20 ]]
	then
		BCOLOR=$WHITE
	else
		BCOLOR=$RED
	fi
	echo -n $(F $BATTERY $BCOLOR)
}

layout() {
	echo -n "$(A $(F $(xkb-switch) $WHITE) layout)"
}

desktops() {
	for i in 1 2 3 4 5
	do
		if [[ $i -eq $(bspc query -D -d) ]]
		then
			printf '%s' "%{A:$i:}$(F "-%{U#ff$WHITE}%{+o}-" $BLACK)$(F $i $WHITE)$(F '-%{-o}%{U-}' $BLACK)%{A}"
		elif [[ -n "$(bspc query -W -d "^$i" | tr '\n' ' ')" ]]
		then
			printf '%s' "%{A:$i:}$(F "-%{U#ff808080}%{+o}-" $BLACK)$(F $i $WHITE)$(F '-%{-o}%{U-}' $BLACK)%{A}"
		else
			printf '%s' "%{A:$i:}$(F '--' $BLACK)$(F $i $WHITE)$(F '-' $BLACK)%{A}"
		fi
	done
}

while true
do
	# Left
	#printf '%s' '%{l}'
	#desktops
	
	# Center
	#printf '%s' '%{c}'
	
	# Right
	printf '%s' '%{r}'
	printf ' %s' $(network) $DIV 
	printf ' %s' $(layout) $DIV
	printf ' %s' $(volume) $DIV 
	# printf ' %s' $(battery) $DIV 
	printf ' %s' $(calendar)

	sleep 0.5s
done | bar_wrapper | ~/.config/bspwm/spawner
