#!/bin/bash
#
# Spawner for Bar Ain't Recursive
#

while read cmd
do
	case "$cmd" in
		volume) pamixer --toggle-mute ;;
		layout) xkb-switch --next ;;
		 [1-5])
#				.config/bspwm/desktopmngr $cmd
				bspc desktop -f ^$cmd ;;
		     *) $cmd ;;
	esac
done
