#!/bin/bash
#
# sxhkdrc by Ivan Sokolov

# Hotkeys for bspwm

# Quit
super + alt + Escape
	pamixer --get-volume > ~/.volume; \
	bspc quit

# Windows #################################################

# Balance tree
super + b
	bspc desktop -B 

# Toggle windows params
super + {q, w, e, r, t, y}
	bspc window -t {floating,fullscreen,pseudo_tiled,locked,sticky,private}

# Close window
alt + w
	bspc window -c

# Move focus
super + {h,j,k,l}
	bspc window -f {left,down,up,right}

# Swap windows
super + shift + {h,j,k,l}
	bspc window -s {left,down,up,right}

# Presel
super + ctrl + {h,j,k,l}
	bspc window -p {left,down,up,right}

# Move to prev\next desktop
super + alt + {h,l}
	bspc window -d {prev,next}

# Move to prev\next monitor
super + alt + {j,k}
	bspc window -m {prev,next}

# Mirror and flip leaves of tree
super + {comma,period}
	bspc desktop -F {horizontal,vertical}

# Rotate leaves of tree
super + shift + {comma,period}
	bspc desktop -R {90,270}

# Desktops ################################################

super + {1-9}
	bspc desktop -f ^{1-9}

# Mouse ###################################################

~button1
	bspc pointer -g focus

super + button{1-3}
	bspc pointer -g {move,resize_side,resize_corner}

super + !button{1-3}
	bspc pointer -t %i %i

super + @button{1-3}
	bspc pointer -u

# Applications ############################################

# URxvt
super + Return
	urxvt
# XTerm
super + alt + Return
	xterm

# dmenu
super + space
	dmenu_wrapper

# Reload sxhkd
super + Escape
	pkill -USR1 -x sxhkd

# Fn's
XF86AudioLowerVolume
	pamw -d 5

XF86AudioRaiseVolume
	pamw -i 5

XF86MonBrightnessDown
	xbacklight -dec 10 -time 500 -steps 50; \
	sleep 0.75s

XF86MonBrightnessUp
	xbacklight -inc 10 -time 500 -steps 50; \
	sleep 0.75s
