#!/bin/bash
#
# sxhkdrc


# Finish bspwm session
ctrl + alt + Delete
	pamixer --get-volume > ~/.volume; \
	bspc quit

# Reload sxhkd config
ctrl + alt + Insert
	pkill -USR1 -x sxhkd


# Windows #####################################################################

# Balance tree
super + b
	bspc desktop -B

# Toggle windows state
super + {q, w, e, a, s, d}
	bspc window -t {floating,fullscreen,pseudo_tiled,locked,sticky,private}


# Close window
super + Escape
	bspc window -c

# Move focus
super + {h,j,k,l}
	bspc window -f {left,down,up,right}

# Swap windows
super + shift + {h,j,k,l}
	bspc window -s {left,down,up,right}

# Presel
super + ctrl + {h,j,k,l}
	bspc window -p {left,down,up,right}

# Split ratio
super + ctrl + {1-9}
	bspc window -r 0.{1-9}

# Desktops ####################################################################

super + {1-9,0}
	bspc desktop -f ^{1-10}

# Mouse #######################################################################

~button1
	bspc pointer -g focus

super + button{1-3}
	bspc pointer -g {move,resize_side,resize_corner}

super + !button{1-3}
	bspc pointer -t %i %i

super + @button{1-3}
	bspc pointer -u

# Applications ################################################################

# URxvt
super + Return
	urxvt
# XTerm
super + alt + Return
	xterm

# dmenu
super + space
	dmenuw

# termspawn
#super + alt + space
#	termspawn

# Fn's
XF86AudioLowerVolume
	pamixer --decrease 5

XF86AudioRaiseVolume
	pamixer --increase 5

XF86MonBrightnessDown
	xbacklight -dec 10 -time 0 -steps 0; \
	sleep 0.5s

XF86MonBrightnessUp
	xbacklight -inc 10 -time 0 -steps 0; \
	sleep 0.5s

XF86AudioNext
	mpc next

XF86AudioPrev
	mpc prev

XF86AudioPlay
	mpc toggle

XF86AudioStop
	mpc stop
